# Ghost SuperComputer — Suga-Native Setup Script
# Run this in PowerShell to configure everything

$ErrorActionPreference = "Continue"
$REPO_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$ENV_FILE = "$REPO_DIR\.env"

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  GHOST SUPERCOMPUTER — SUGA-NATIVE SETUP" -ForegroundColor Cyan
Write-Host "  1 tool (Suga) | $0/month | No credit card" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# ============================================================
# STEP 1: Suga Account
# ============================================================
Write-Host "[STEP 1/5] SUGA.APP" -ForegroundColor Yellow
Write-Host "  Opening Suga signup..." -ForegroundColor Gray
Start-Process "https://suga.app/sign-up"
Write-Host ""
Write-Host "  Instructions:" -ForegroundColor White
Write-Host "  1. Sign up at suga.app (no CC needed)" -ForegroundColor Gray
Write-Host "  2. Create new project" -ForegroundColor Gray
Write-Host "  3. Connect GitHub repo or paste URL" -ForegroundColor Gray
Write-Host "  4. Add services from templates (see below)" -ForegroundColor Gray
Write-Host ""

Write-Host "  Templates to add:" -ForegroundColor White
Write-Host "    1. PostgreSQL" -ForegroundColor Gray
Write-Host "    2. PocketBase" -ForegroundColor Gray
Write-Host "    3. MinIO" -ForegroundColor Gray
Write-Host "    4. Meilisearch" -ForegroundColor Gray
Write-Host "    5. LiteLLM" -ForegroundColor Gray
Write-Host "    6. n8n" -ForegroundColor Gray
Write-Host "    7. Uptime Kuma" -ForegroundColor Gray
Write-Host "    8. Grafana" -ForegroundColor Gray
Write-Host "    9. Custom Docker (gitagent)" -ForegroundColor Gray
Write-Host ""

# ============================================================
# STEP 2: LLM API Keys
# ============================================================
Write-Host "[STEP 2/5] LLM API KEYS" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Option A: GitHub Models (free GPT-4o-mini)" -ForegroundColor White
Start-Process "https://github.com/settings/tokens"
Write-Host "  - Create token with 'models:read' scope" -ForegroundColor Gray
Write-Host ""

$GITHUB_TOKEN = Read-Host "  Paste GitHub token (ghp_xxx) or Enter to skip"

Write-Host ""
Write-Host "  Option B: OpenAI (free $5 credit)" -ForegroundColor White
Start-Process "https://platform.openai.com/api-keys"
$OPENAI_KEY = Read-Host "  Paste OpenAI key (sk-xxx) or Enter to skip"

# ============================================================
# STEP 3: Suga Service Credentials
# ============================================================
Write-Host ""
Write-Host "[STEP 3/5] SUGA SERVICE CREDENTIALS" -ForegroundColor Yellow
Write-Host "  Go to each service in Suga dashboard and copy credentials" -ForegroundColor Gray
Write-Host ""

$DATABASE_URL = Read-Host "  PostgreSQL connection string"
$POCKETBASE_ANON_KEY = Read-Host "  PocketBase anon key"
$MINIO_ACCESS_KEY = Read-Host "  MinIO access key"
$MINIO_SECRET_KEY = Read-Host "  MinIO secret key"
$MEILI_MASTER_KEY = Read-Host "  Meilisearch master key"

# ============================================================
# STEP 4: Generate .env
# ============================================================
Write-Host ""
Write-Host "[STEP 4/5] GENERATING CONFIG" -ForegroundColor Yellow

$PB_PASS = -join ((1..16) | ForEach-Object { [char](Get-Random -Min 97 -Max 123) })

$envContent = @"
# Ghost SuperComputer — Suga-Native Configuration
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# GENERAL
GHOST_ENV=production
GHOST_PUBLIC_HOST=localhost
TZ=UTC

# POSTGRESQL (Suga template)
DATABASE_URL=$DATABASE_URL

# POCKETBASE (Suga template)
POCKETBASE_URL=http://pocketbase:8090
POCKETBASE_ANON_KEY=$POCKETBASE_ANON_KEY
POCKETBASE_ADMIN_EMAIL=admin@ghost.local
POCKETBASE_ADMIN_PASSWORD=$PB_PASS

# MINIO (Suga template)
MINIO_ENDPOINT=http://minio:9000
MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
MINIO_SECRET_KEY=$MINIO_SECRET_KEY

# MEILISEARCH (Suga template)
MEILI_URL=http://meilisearch:7700
MEILI_MASTER_KEY=$MEILI_MASTER_KEY

# LITELLM (Suga template)
LITELLM_URL=http://litellm:4000

# LLM API KEYS
GITHUB_TOKEN=$GITHUB_TOKEN
OPENAI_API_KEY=$OPENAI_KEY

# SUGA.APP (update after creating service)
SUGA_HOST=ghost-xxx.suga.app
SUGA_PORT=3333
"@

$envContent | Out-File -FilePath $ENV_FILE -Encoding utf8
Write-Host "  [OK] .env file created" -ForegroundColor Green

# ============================================================
# STEP 5: Git Push
# ============================================================
Write-Host ""
Write-Host "[STEP 5/5] GIT PUSH" -ForegroundColor Yellow

Set-Location $REPO_DIR
git add -A
git status

$commit = Read-Host "  Commit changes? (y/n)"
if ($commit -eq "y") {
    git commit -m "Configure Suga-native environment"
    git push
    Write-Host "  [OK] Pushed to GitHub" -ForegroundColor Green
}

# ============================================================
# SUMMARY
# ============================================================
Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "  SETUP COMPLETE!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Suga will auto-deploy on push." -ForegroundColor White
Write-Host ""
Write-Host "  After deploy:" -ForegroundColor White
Write-Host "  1. Run schema.sql in Suga PostgreSQL SQL Editor" -ForegroundColor Gray
Write-Host "  2. Setup cron-job.org keep-alive" -ForegroundColor Gray
Write-Host ""
Write-Host "  Your services:" -ForegroundColor White
Write-Host "    Agent:    https://YOUR_SUGA_HOST/api/agent/" -ForegroundColor Cyan
Write-Host "    n8n:      https://YOUR_SUGA_HOST/n8n/" -ForegroundColor Cyan
Write-Host "    PocketBase: https://YOUR_SUGA_HOST/pb/" -ForegroundColor Cyan
Write-Host "    MinIO:    https://YOUR_SUGA_HOST/minio/" -ForegroundColor Cyan
Write-Host "    Meili:    https://YOUR_SUGA_HOST/meilisearch/" -ForegroundColor Cyan
Write-Host "    LiteLLM:  https://YOUR_SUGA_HOST/litellm/" -ForegroundColor Cyan
Write-Host "    Uptime:   https://YOUR_SUGA_HOST/uptime-kuma/" -ForegroundColor Cyan
Write-Host "    Grafana:  https://YOUR_SUGA_HOST/grafana/" -ForegroundColor Cyan
Write-Host "    Health:   https://YOUR_SUGA_HOST/api/health" -ForegroundColor Cyan
Write-Host ""
